export { default as Hero } from "./Hero"
export { default as UsageGuide } from "./UsageGuide"
export { default as CustomerReviews } from "./CustomerReviews"
export { default as JoinFastSchool } from "./JoinFastSchool"
export { default as Contact } from "./Contact"